[build]
  command = "cd lady-rewards/frontend && npm install && npm run build && cp -r dist ../../LadyRipple-Website-Package/rewards && cp -r dist ../../LadyRipple-Website-Package/swap"
  publish = "LadyRipple-Website-Package"

[[redirects]]
  from = "/rewards/*"
  to = "/rewards/index.html"
  status = 200

[[redirects]]
  from = "/swap/*"
  to = "/swap/index.html"
  status = 200
